# Generated by Django 5.2.5 on 2026-02-08 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_profile_education_workexperience_userskill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_skills",
                to="app.skill",
            ),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
