# Generated by Django 5.2.5 on 2026-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_paymenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="card_mask",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="card_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
