# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0071_usersubscription_card_mask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsession",
            name="dont_know_per_skill",
            field=models.JSONField(default=dict),
        ),
    ]
