# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0072_assessmentsession_dont_know_per_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamictechquestion",
            name="option5",
            field=models.CharField(default="I don't know", max_length=255),
        ),
        migrations.AddField(
            model_name="dynamicsoftskillsquestion",
            name="option5",
            field=models.CharField(default="I don't know", max_length=255),
        ),
    ]
