# Generated by Django 5.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_add_option5_to_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("salary_info", models.JSONField(default=dict, help_text='{"min": 70000, "max": 120000, "currency": "USD", "display": "$70,000 - $120,000"}')),
                ("market_popularity", models.JSONField(default=list, help_text='[{"year": "2020", "value": 75}, {"year": "2021", "value": 80}, ...] for charts')),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("relevant_courses", models.ManyToManyField(blank=True, related_name="professions", to="app.course")),
                ("skills", models.ManyToManyField(blank=True, related_name="professions", to="app.skill")),
            ],
        ),
    ]
