# Generated by Django 5.2.5

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_profession"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionOfUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_score", models.FloatField(default=0.0, help_text="Percentage (0-100) of profession skills the user has with SkillScore > 0")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("profession", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_assignments", to="app.profession")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profession_assignments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-match_score"],
            },
        ),
        migrations.AddConstraint(
            model_name="professionofuser",
            constraint=models.UniqueConstraint(fields=("user", "profession"), name="unique_user_profession"),
        ),
    ]
