# Generated by Django 5.2.5 on 2026-02-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_professionofuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilltestresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="profession",
            name="salary_info",
            field=models.JSONField(
                default=dict,
                help_text="Object: US, Germany, Georgia, Turkey, UK, Other -> {min, max, currency, display}",
            ),
        ),
    ]
