# Generated by Django 5.2.5 on 2026-03-26 18:50

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_course_cover_image_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='course_covers/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer_photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='lecturer_photos/'),
        ),
    ]
