# Generated by Django 5.2.5 on 2026-03-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_alter_course_cover_image_alter_course_lecturer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
