# Generated by Django 5.2.5 on 2026-04-01 19:32

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_course_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('number_of_employees', models.CharField(blank=True, default='', max_length=100)),
                ('industry_names', models.JSONField(blank=True, default=list, help_text='List of industry name strings; Industry rows are created/linked on verify.')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('description', models.TextField(default='No description provided')),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='employer_logos/')),
                ('locations', models.JSONField(blank=True, default=list, help_text='List of strings, e.g. ["Tbilisi, Georgia", "Remote"]')),
                ('number_of_employees', models.CharField(blank=True, default='', help_text='e.g. "1-10", "11-50", "1000+"', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
                ('industries', models.ManyToManyField(blank=True, related_name='employers', to='app.industry')),
            ],
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='app.employer'),
        ),
    ]
