# Generated by Django 5.2.5 on 2026-04-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_industry_temporaryemployer_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='password',
        ),
    ]
