# Generated by Django 5.2.5 on 2026-04-04 00:48

from django.db import migrations, models


def copy_temp_company_name_to_first_name(apps, schema_editor):
    TemporaryEmployer = apps.get_model("app", "TemporaryEmployer")
    for row in TemporaryEmployer.objects.all():
        if not (row.first_name or "").strip() and getattr(row, "company_name", None):
            row.first_name = row.company_name
            row.save(update_fields=["first_name"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0081_remove_employer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="role_in_company",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Job title or role (e.g. HR Manager, Founder).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="temporaryemployer",
            name="first_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="temporaryemployer",
            name="last_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="temporaryemployer",
            name="role_in_company",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(copy_temp_company_name_to_first_name, noop_reverse),
        migrations.RemoveField(
            model_name="employer",
            name="description",
        ),
        migrations.RemoveField(
            model_name="employer",
            name="industries",
        ),
        migrations.RemoveField(
            model_name="employer",
            name="locations",
        ),
        migrations.RemoveField(
            model_name="employer",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="employer",
            name="number_of_employees",
        ),
        migrations.RemoveField(
            model_name="employer",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="employer",
            name="website",
        ),
        migrations.RemoveField(
            model_name="temporaryemployer",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="temporaryemployer",
            name="description",
        ),
        migrations.RemoveField(
            model_name="temporaryemployer",
            name="industry_names",
        ),
        migrations.RemoveField(
            model_name="temporaryemployer",
            name="locations",
        ),
        migrations.RemoveField(
            model_name="temporaryemployer",
            name="number_of_employees",
        ),
        migrations.RemoveField(
            model_name="temporaryemployer",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="temporaryemployer",
            name="website",
        ),
    ]
