# Generated by Django 5.2.5 on 2026-07-07 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "title"],
                        name="app_learnin_is_acti_6f3b2a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Atom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "sequence_order",
                    models.PositiveIntegerField(
                        help_text="Strict ordering within the module (1 = first atom)."
                    ),
                ),
                ("content_cards", models.JSONField(blank=True, default=list)),
                ("quiz_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atoms",
                        to="app.learningmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["module", "sequence_order"],
                "indexes": [
                    models.Index(
                        fields=["module", "sequence_order"],
                        name="app_atom_module__a1b2c3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_percentage", models.FloatField(default=0.0)),
                ("is_completed", models.BooleanField(default=False)),
                ("requires_retake", models.BooleanField(default=False)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "atom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="app.atom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atom_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "atom"],
                        name="app_userpro_user_id_d4e5f6_idx",
                    ),
                    models.Index(
                        fields=["user", "is_completed"],
                        name="app_userpro_user_id_g7h8i9_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="atom",
            constraint=models.UniqueConstraint(
                fields=("module", "sequence_order"),
                name="unique_atom_sequence_per_module",
            ),
        ),
        migrations.AddConstraint(
            model_name="userprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "atom"),
                name="unique_user_atom_progress",
            ),
        ),
    ]
