# Generated by Django 5.2.5 on 2026-07-07 00:47

import app.atom_schemas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0084_atoms"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="atom",
            new_name="app_atom_module__f1c3e3_idx",
            old_name="app_atom_module__a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="learningmodule",
            new_name="app_learnin_is_acti_2835d5_idx",
            old_name="app_learnin_is_acti_6f3b2a_idx",
        ),
        migrations.RenameIndex(
            model_name="userprogress",
            new_name="app_userpro_user_id_6a4c90_idx",
            old_name="app_userpro_user_id_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="userprogress",
            new_name="app_userpro_user_id_55b520_idx",
            old_name="app_userpro_user_id_g7h8i9_idx",
        ),
        migrations.AlterField(
            model_name="atom",
            name="content_cards",
            field=models.JSONField(
                blank=True,
                default=app.atom_schemas.default_content_cards,
                help_text='Story-like cards shown in order. content_type must be one of: markdown, code, math_formula, rich_text. card_index starts at 0.\n\nExample:\n[\n  {\n    "card_index": 0,\n    "content_type": "markdown",\n    "content_body": "# What is a React Component?\\n\\nA **component** is a reusable piece of UI \\u2014 like a LEGO brick for your interface."\n  },\n  {\n    "card_index": 1,\n    "content_type": "code",\n    "content_body": "function Welcome() {\\n  return <h1>Hello, Breneo!</h1>;\\n}\\n\\nexport default Welcome;"\n  },\n  {\n    "card_index": 2,\n    "content_type": "math_formula",\n    "content_body": "Rendering cost \\u2248 O(n) where n = number of DOM nodes updated per render."\n  },\n  {\n    "card_index": 3,\n    "content_type": "rich_text",\n    "content_body": "<p>Tip: Keep components <strong>small</strong> and focused on one job.</p>"\n  }\n]',
            ),
        ),
        migrations.AlterField(
            model_name="atom",
            name="quiz_data",
            field=models.JSONField(
                blank=True,
                default=app.atom_schemas.default_quiz_data,
                help_text='End-of-lesson quiz. Exactly 3 options; correct_index is 0, 1, or 2. Passing score is 80%.\n\nExample:\n{\n  "options": [\n    "A reusable piece of UI",\n    "A database table",\n    "A CSS stylesheet"\n  ],\n  "correct_index": 0,\n  "explanation": "React components are reusable building blocks that describe what should appear on screen."\n}',
            ),
        ),
    ]
