# Generated by Django 5.2.5 on 2026-07-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0086_atoms_use_profession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profession",
            name="salary_info",
        ),
    ]
